name: CI
on: [push, pull_request]
jobs:
  validate_katacoda:
    name: Validate Katacoda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Katacoda CLI
        run: |
          sudo npm i katacoda-cli markdownlint-cli --global
      - name: Validate Katacoda scenarios
        run: |
          katacoda validate:all --repo ${{ github.workspace }}
      - name: Validate Katacoda Markdown
        run: |
          markdownlint '**/*.md' --ignore node_modules
