name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate_katacoda:
    name: Validate Katacoda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install validators CLI tools
        run: |
          sudo npm i katacoda-cli markdownlint-cli --global
      - name: Validate Katacoda scenarios
        run: |
          katacoda validate:all --repo ${{ github.workspace }}
      - name: Validate Markdown
        run: |
          markdownlint '**/*.md' --ignore node_modules
